### ISSUE TITLE
ignoreOp

### ISSUE THREAD

**Issue by Romaq** [Phoenix616/BetterBeds#9]
I have a very tiny server for which everyone has /op. Because of this, everyone is *ignored* by this plugin. I want to avoid setting up a Permissions plugin since we will likely revert back to Vanilla on future snapshots. I would be using https://xisumavoid.com/vanillatweaks/ "Multiplayer Sleeping" data pack, but it doesn't appear to be working under the current Vanilla version 1.13.1. 

I would like the means to have the config "ignoreOp" with a default of true so it will not affect current installs, but I would be able to tell BetterBeds to allow our players to sleep even though we have /op.

Thank you for considering this request.

**Comment by Phoenix616** [comment]
Ops are [not ignored](https://github.com/Phoenix616/BetterBeds/blob/master/src/main/resources/plugin.yml#L30) by default, please make sure that you are actually using the latest build of the plugin.

**Comment by Romaq** [comment]
Thank you, it works. I grabbed the one on the Spigot page, I believe. I apologize for not seeing this was not the latest.
